fail_fast: true
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
    -   id: flake8
        args:
        - --max-line-length=160
        - --exclude=*/migrations/*,docs/*
        - --ignore=E126
    -   id: check-added-large-files
- repo: git://github.com/ambv/black
  rev: 18.9b0
  hooks:
    - id: black
      args: [--line-length=120, --safe]
