language: python
dist: xenial
python:
  - 2.7
  - 3.5
  - 3.6
  - 3.7

install:
  - pip install tox-travis
  - pip install -e .[for_tests]
script:
  - nosetests

notifications:
  email:
    on_failure: change
    on_success: never
